// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjR2DSMmYy3rCh8Q021D18hhnc77853GA',
    appId: '1:747244538251:web:c390d77e447a8603b0478e',
    messagingSenderId: '747244538251',
    projectId: 'devlingo-be146',
    authDomain: 'devlingo-be146.firebaseapp.com',
    storageBucket: 'devlingo-be146.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPs2ScnlWk_p5BN9k3sTbYmUs0vY8Owyw',
    appId: '1:747244538251:android:c5ced52e043bc4c8b0478e',
    messagingSenderId: '747244538251',
    projectId: 'devlingo-be146',
    storageBucket: 'devlingo-be146.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKgmOlbkWrs2Vxmib7OY-hpMnP_Fo7Rps',
    appId: '1:747244538251:ios:1d1c2e6a57b89351b0478e',
    messagingSenderId: '747244538251',
    projectId: 'devlingo-be146',
    storageBucket: 'devlingo-be146.firebasestorage.app',
    iosBundleId: 'com.example.devlingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgmOlbkWrs2Vxmib7OY-hpMnP_Fo7Rps',
    appId: '1:747244538251:ios:1d1c2e6a57b89351b0478e',
    messagingSenderId: '747244538251',
    projectId: 'devlingo-be146',
    storageBucket: 'devlingo-be146.firebasestorage.app',
    iosBundleId: 'com.example.devlingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjR2DSMmYy3rCh8Q021D18hhnc77853GA',
    appId: '1:747244538251:web:67a6c78bce2b5a05b0478e',
    messagingSenderId: '747244538251',
    projectId: 'devlingo-be146',
    authDomain: 'devlingo-be146.firebaseapp.com',
    storageBucket: 'devlingo-be146.firebasestorage.app',
  );
}
